const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  getData:          ()      => ipcRenderer.invoke('get-data'),
  saveTabs:         (tabs)  => ipcRenderer.invoke('save-tabs', tabs),
  saveHistory:      (h)     => ipcRenderer.invoke('save-history', h),
  saveMaxHistory:   (n)     => ipcRenderer.invoke('save-max-history', n),
  setShortcut:      (key)   => ipcRenderer.invoke('set-shortcut', key),
  writeClipboard:   (text)  => ipcRenderer.invoke('write-clipboard', text),
  hideWindow:       ()      => ipcRenderer.invoke('hide-window'),
  pasteText:        (text)  => ipcRenderer.invoke('paste-text', text),
  openSettings:     ()      => ipcRenderer.invoke('open-settings'),
  exportData:       (fmt)   => ipcRenderer.invoke('export-data', fmt),
  importData:       (fmt, overwrite) => ipcRenderer.invoke('import-data', fmt, overwrite),
  uninstall:        ()      => ipcRenderer.invoke('uninstall'),
  openExternal:     (url)   => ipcRenderer.invoke('open-external', url),
  checkUpdate:      ()      => ipcRenderer.invoke('check-update'),
  getAppVersion:    ()      => ipcRenderer.invoke('get-app-version'),
  onHistoryUpdated: (cb)    => ipcRenderer.on('history-updated', (_, d) => cb(d)),
  onTabsUpdated:    (cb)    => ipcRenderer.on('tabs-updated',    (_, d) => cb(d)),
  onSettingsClosed: (cb)    => ipcRenderer.on('settings-closed', ()    => cb()),
});
